const ActionTypes = {
	FETCH_CHAPTER: "FETCH_CHAPTER",
	ADD_CHAPTER: "ADD_CHAPTER:",
	GET_CHAPTER: "GET_CHAPTER",
	CHAPTER_WAS_CHANGED: "CHAPTER_WAS_CHANGED",
	KEEP_AND_CLEAR_CHAPTER: "KEEP_AND_CLEAR_CHAPTER",
	UPDATE_SEARCH: "UPDATE_SEARCH",
	FETCH_VERSE: "FETCH_VERSE",
	GET_VERSE: "GET_VERSE",
	
	REQUEST_LOGIN_USER: "REQUEST_LOGIN_USER",
    REQUEST_LOGIN_USER_SUCCESS: "REQUEST_LOGIN_USER_SUCCESS",
    REQUEST_LOGIN_USER_ERROR: "REQUEST_LOGIN_USER_ERROR"
	  
};

export default ActionTypes;