const ActionTypes = {

	ADD_CHAPTER: "ADD_CHAPTER:",

	BIBLE_URL_CHANGED:"BIBLE_URL_CHANGED",

	CHAPTER_WAS_CHANGED: "CHAPTER_WAS_CHANGED",
	CLEAR_VERSE:"CLEAR_VERSE",
	CREATE_LIST_CHILD:"CREATE_LIST_CHILD",
	
	NOTE_FIND:"NOTE_FIND",
	NOTE_GET:"NOTE_GET",
	NOTE_CREATE:"NOTE_CREATE",
	NOTE_UPDATE:"NOTE_UPDATE",
	NOTE_DESTROY:"NOTE_DESTROY",
	NOTE_DESTROY_COMPLETED:"NOTE_DESTROY_COMPLETED",
	
	FETCH_CHAPTER: "FETCH_CHAPTER",
	FETCH_FAILED: "FETCH_FAILED",
	FETCHED_BAD_REFERENCE: "FETCHED_BAD_REFERENCE",
	FETCH_VERSE: "FETCH_VERSE",
	
	FETCH_LIST: "FETCH_LIST",
	
	GET_CHAPTER: "GET_CHAPTER",
	GET_VERSE: "GET_VERSE",
	
	KEEP_AND_CLEAR_CHAPTER: "KEEP_AND_CLEAR_CHAPTER",
	
	LIST_TOGGLE_COMPLETE_ALL:"LIST_TOGGLE_COMPLETE_ALL",  
	LOGOUT_USER:"LOGOUT_USER",
	
	REQUEST_LOGIN_USER: "REQUEST_LOGIN_USER",
    REQUEST_LOGIN_USER_SUCCESS: "REQUEST_LOGIN_USER_SUCCESS",
    REQUEST_LOGIN_USER_ERROR: "REQUEST_LOGIN_USER_ERROR",
	
	REQUEST_USER: "REQUEST_USER",
    REQUEST_USER_SUCCESS: "REQUEST_USER_SUCCESS",
    REQUEST_USER_ERROR: "REQUEST_USER_ERROR",
	
	UPDATE_SEARCH: "UPDATE_SEARCH"
};

export default ActionTypes;