var appConstants = {
	FETCH_CHAPTER: "FETCH_CHAPTER",
	ADD_CHAPTER: "ADD_CHAPTER:",
	GET_CHAPTER: "GET_CHAPTER",
	CHAPTER_WAS_CHANGED: "CHAPTER_WAS_CHANGED",
	KEEP_AND_CLEAR_CHAPTER: "KEEP_AND_CLEAR_CHAPTER",
	UPDATE_SEARCH: "UPDATE_SEARCH"
};

export default appConstants;